"""
This file contains Pydantic models that represent the final LLM Response.
"""

from typing import Any, Dict, List, Optional, Union

from langchain_core.pydantic_v1 import BaseModel, Field


class Response(BaseModel):
    """
    Final response to the question being asked
    """

    question: str = Field(description="The question asked by the user.")
    sub_questions: Optional[List[str]] = Field(
        description="The sub questions that are found by the LLM within the original question.",
        default=None,
    )
    answer: str = Field(description="The final answer to respond to the user.")

    cypher: Optional[Union[List[str], str]] = Field(
        description="The cypher used to retrieve the results. Only present if cypher is generated by the LLM.",
        default=None,
    )
    cypher_result: Optional[Union[List[List[Dict[str, Any]]], List[Dict[str, Any]]]] = (
        Field(
            description="The result from the cypher query. Only present if cypher is generated by the LLM.",
            default=None,
        )
    )

    def display(self) -> None:
        """
        Print the response object nicely.
        """

        base = f"""
Question:
{self.question}
"""
        if self.sub_questions:
            q = ""
            for q in self.sub_questions:
                q += "\n"
            base += f"""
Sub Questions:
{q}
            """

        if self.cypher:
            base += f"""
Cypher: {self.cypher}

Cypher Result:
{self.cypher_result}
            """

        base += f"""
Final Response:
{self.answer}
        """

        print(base)
